# Generated by Django 4.0.3 on 2022-04-09 04:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='contents',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
