# Generated by Django 4.0.3 on 2022-04-09 04:18

from django.db import migrations, models
import guide.models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_guide_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='tags',
            field=models.JSONField(default=guide.models.tag_default, verbose_name='tags'),
        ),
    ]
