# Generated by Django 4.0.3 on 2022-04-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_guide_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
