# Generated by Django 4.0.3 on 2022-04-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='region',
            field=models.CharField(choices=[('TO', 'Tokyo'), ('KY', 'Kyoto'), ('OS', 'Osaka')], default='TO', max_length=2),
        ),
    ]
