# Generated by Django 4.0.3 on 2022-04-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_alter_destination_image_alter_destination_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='map_link',
            field=models.URLField(default='https://www.google.com/maps'),
        ),
    ]
