# Generated by Django 4.0.3 on 2022-04-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_alter_destination_location_alter_destination_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='region',
            field=models.CharField(choices=[('TO', 'Tokyo'), ('KA', 'Kansai'), ('TK', 'Tohoku'), ('HK', 'Hokkaido'), ('KY', 'Kyushu'), ('SK', 'Shikoku')], default=('TO', 'Tokyo'), max_length=2),
        ),
    ]
