# Generated by Django 4.0.3 on 2022-04-06 16:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0006_alter_destination_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
