# Generated by Django 4.0.3 on 2022-04-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0007_alter_destination_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.CharField(default='https://i.ibb.co/RvmN9CH/Biwako-Sunset.jpg', max_length=200),
        ),
    ]
