# Generated by Django 4.0.3 on 2022-04-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0008_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='location',
            field=models.CharField(choices=[('UAA', 'Ueno/Asakusa/Akihabara'), ('IKE', 'Ikebukuro'), ('SNK', 'Shinjuku/Nakano/Kichioji'), ('ARO', 'Asakasa/Roppongi'), ('SHS', 'Shibuya/Harajuku/Shimokitazawa'), ('SME', 'Shinagawa/Meguro/Ebisu'), ('KYT', 'Kyoto'), ('SAP', 'Sapporo')], default=('UAA', 'Ueno/Asakusa/Akihabara'), max_length=3),
        ),
    ]
